import { afterEach, expect, it, vi } from 'vitest';
import { createVideoProvider } from '../src/video.mjs';

afterEach(() => vi.restoreAllMocks());

it.each([5, 30])('resumes a submitted Seedance job with its saved %i-second cadence without generating again', async pollSeconds => {
  const saved = new Map(), cache = new Map(), calls = [];
  let suspended = false, polls = 0;
  const step = {
    async do(name, config, callback = config) {
      if (saved.has(name)) return structuredClone(saved.get(name));
      const value = await callback(); saved.set(name, structuredClone(value)); return value;
    },
    async sleep(_name, duration) {
      expect(duration).toBe(`${pollSeconds} seconds`);
      if (!suspended) { suspended = true; throw new Error('Aborting engine: User called pause'); }
    },
  };
  const asset = { mediaHash: 'test-video', mediaType: 'video', url: '/assets/test.mp4' };
  const media = { ingestMedia: vi.fn(async stream => {
    expect(await new Response(stream).text()).toBe('generated bytes');
    return asset;
  }) };
  const store = { cachedJson: async key => cache.get(key), saveCachedJson: async (key, value) => cache.set(key, value) };
  vi.spyOn(globalThis, 'fetch').mockImplementation(async (url, options) => {
    calls.push({ url: String(url), method: options.method });
    if (options.method === 'POST') {
      expect(options.headers['Idempotency-Key']).toMatch(/^[a-f0-9]{64}$/);
      return Response.json({ id: 'saved-job' });
    }
    if (String(url).endsWith('/content')) return Response.json({ url: 'https://cdn.example.test/video.mp4' });
    if (String(url).endsWith('/jobs/saved-job')) return Response.json({ status: polls++ ? 'completed' : 'queued' });
    expect(options.headers['X-API-Key']).toBeUndefined();
    return new Response('generated bytes');
  });
  const render = () => createVideoProvider({ PIKA_API_KEY: 'test' }, media, store, { step, checkpoint: async () => {}, pollSeconds });
  const brief = { aspectRatio: '1:1', videoDuration: 5 };
  await expect(render()('Notebook ad', brief)).rejects.toThrow('User called pause');
  expect(await render()('Notebook ad', brief)).toEqual(asset);
  expect(calls.filter(call => call.method === 'POST')).toHaveLength(1);
  expect(media.ingestMedia).toHaveBeenCalledOnce();
  expect(cache.values().next().value).toEqual({ id: 'saved-job', asset });
});
